name: flutter_2048
description: 2048 game

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+2
  flutter_launcher_icons: ^0.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true 
  ios: true
  image_path: "asset/icon.png"
  image_path_android: "asset/icon.png"
  image_path_ios: "asset/icon.png"

flutter:
  uses-material-design: true
  assets:
    - icon.png
  fonts:
    - family: StarJedi
      fonts:
        - asset: font/starjedi.ttf
        
        
  
  
  
  
  
  
  
  
